<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <title>catch方法</title>
</head>

<body>
  <script>
    // 指定 Promise 失败的一个回调
    const p = new Promise((resolve, reject) => {
      setTimeout(() => {
        // 设置 p 对象的状态为失败，并设置失败的值
        reject('出错了！')
      }, 1000)
    })

    // 通过 then 的失败回调
    // p.then(value => { }, reason => {
    //   console.error(reason)
    // })

    // 通过 catch 方法来指定 失败 的回调
    p.catch(reason => {
      console.warn(reason)
    })

  </script>
</body>

</html>